---
title: "Initial EDA Basic Outline"
author: "Daniel Gao"
output: html_notebook
---

This is an outline for your Initial EDA. You can follow this outline, or you can modify it as you see fit. Do what works best for your project. 

## Research Question 

State your specific research question and why it is interesting. 

**Introduction**

  The video game industry is growing and will continue to stay prominent. One industry that has grown from the rise of video games is electronic sports. Electrnoic sports, otherwise known as Esports, is the competitive aspect of video games, where players compete in tournament for a select game. What are the popularity differences between video games, and how do they vary in earnings?


## Data Processing 

#### Data Intake 

Include R code and written explanation to import your **TWO** data sets.

**Importing The Data**
Both datasets "GenralEsportData" and "HistoricalEsportData" were taken from [Kaggle.Com](https://www.kaggle.com/datasets/rankirsh/esports-earnings). Since both datasets were csv files, a read.csv() function were used to read the two files. The result of each read function were then assigned to two dataframes "General" and "Historical" respectively.

```{r}
General <- read.csv("GeneralEsportData.csv")
Historical <- read.csv("HistoricalEsportData.csv")
```
#### Data Wrangling 

Write out the origin and purpose (who/what/when/where/why/how data were collected)
Investigate and explain key variables (types, coding, missingness, summary statistics/plots) are clearly presented. 
**Who**: Each video games title 

**What**: The earnings for each tournament. 

**When**: The years are from 1998 to 2023.

**Why**: The goal is to record the data for each Esport tournament.

**Where**: The two datasets do not provide a location.

**How**: The data was collected from 

**Case**:

**How was the data colletect**: The creator obtain his data from [Esports Earnings](https://www.esportsearnings.com/tournaments). Esports Earning stated, "Sources include news articles, forum posts, live report threads, interviews, official statements, reliable databases, VODs and other publicly-accessable sources that preserve "historical" information.


## Data Visualization

#### Plot 1

Include R code to make one data visualization (I would encourage you to use 3 or more variables). Include a brief written description of what your graph shows. Is this graph helpful in answering your research question? If it is helpful, will you need to add/modify anything in this graph in the final report? 

#### Plot 2

Include R code to make one data visualization (I would encourage you to use 3 or more variables). Include a brief written description of what your graph shows. Is this graph helpful in answering your research question? If it is helpful, will you need to add/modify anything in this graph in the final report? 


## Conclusion

Include your initial intuition as to what the answer to your research question is using the data sets and visualizations you created. 